### ISSUE TITLE
CSS problem when reading show notes in a small browser window

### ISSUE THREAD

**Issue by famalgosner** [shownotes/snotes20-angular-webapp#70]
Logo of the podcast and all title information such as title, length etc. overlap when visiting the site with a browser's width smaller than 1500px. (For example: https://shownot.es/culinaricast/99/)

Tested on OSX with Chrome and Safari. No problem with Firefox.

**Comment by luto** [comment]
https://github.com/shownotes/snotes20-angular-webapp/issues/32
