### ISSUE TITLE
play?

### ISSUE THREAD

**Issue by nise** [shownotes/snotes20-angular-webapp#73]
gibt es in der GUI eigentlich einen simplen play-button? wenn ja, wo? FF zeigt mir nichts dergleichen an. 
aus dem lightning talk bei den datenspuren/c3d2 glaubte ich gehört zu haben, es handele sich um einen podcast player mit umfangreicher annotationsfunktionen.

**Comment by Drake81** [comment]
Das hast sicher falsch verstanden. Bisher wird der Podcast live über einen Stream gehört oder wenn nachträglich vershownotet wird über einen lokalen Player.
Die Software bietet aber die Möglichkeit einen solchen Editor/Player noch einzubauen.

**Comment by nise** [comment]
Verstehe. Der Zustand des Systems war mir nicht deutlich geworden. Kommt nun eine Live Stream von irgendwo (URL?) oder wird eine Audiodatei abgespielt (=> Player Interface). Kennt ihr videonot.es ? Dort ist das UI gut geregelt.

**Comment by Drake81** [comment]
Die meisten Podcasts auf Shownot.es werden live über http://streams.xenim.de/ gestreamt.
Die Shownoter klicken sich dort einfach ein.

Die Seite videonot.es ist offline. Kannte ich bisher noch nicht.
